name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git ffmpeg unzip openjdk-11-jdk \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-tools

      # 4️⃣ Install Python dependencies including Cython
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer kivy kivymd plyer reportlab cython

      # 5️⃣ Install Android SDK, NDK & Build-tools
      - name: Install Android SDK & Build-tools
        run: |
          mkdir -p $HOME/Android/Sdk
          cd $HOME/Android/Sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d tmpdir
          mkdir -p cmdline-tools/latest
          mv tmpdir/cmdline-tools/* cmdline-tools/latest/
          rm -rf tmpdir
          
          # Set environment variables
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools:$PATH" >> $GITHUB_ENV
          
          # Accept licenses and install build-tools + platform
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      # 6️⃣ Build APK with Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # 7️⃣ Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VisitorApp-debug.apk
          path: bin/*.apk
