name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.home }}/Android/Sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git wget

    - name: Install Cython and Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Download Android cmdline-tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d tmpdir
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv tmpdir/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
        rm -rf tmpdir cmdline-tools.zip

    - name: Setup Android SDK environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
        sdkmanager --version

    - name: Accept licenses
      run: |
        yes | sdkmanager --licenses

    - name: Install Build-tools, Platform-tools, NDK
      run: |
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

    - name: Build APK
      run: |
        buildozer android debug
