name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.temp }}/android-sdk
      PATH: ${{ runner.temp }}/android-sdk/cmdline-tools/latest/bin:${{ runner.temp }}/android-sdk/platform-tools:${{ env.PATH }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip python3-setuptools python3-wheel \
          git zip unzip openjdk-17-jdk \
          libstdc++6 libz-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          libncurses6 build-essential

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Download Android SDK command line tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        curl -L https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Android SDK packages
      run: |
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: bin/*.apk
