name: Build APK (kivy/buildozer - robust)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the prebuilt image that includes buildozer, p4a, SDK tools etc.
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show environment info (debug)
        run: |
          echo "User: $(id -u -n)"
          python --version || true
          pip --version || true
          buildozer --version || true
          ls -la

      - name: Ensure buildozer.spec has required minimal tokens
        run: |
          # If buildozer.spec missing, fail fast
          if [ ! -f buildozer.spec ]; then
            echo "Error: buildozer.spec not found in repo root" >&2
            exit 1
          fi
          # Ensure source.dir = . exists
          if ! grep -qE '^source\.dir\s*=' buildozer.spec; then
            echo "" >> buildozer.spec
            echo "# auto-added by CI: ensure project root is used" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "Added source.dir = . to buildozer.spec"
          fi
          # Ensure version exists
          if ! grep -qE '^version\s*=' buildozer.spec; then
            echo "" >> buildozer.spec
            echo "# auto-added by CI: default version" >> buildozer.spec
            echo "version = 0.1" >> buildozer.spec
            echo "Added version = 0.1 to buildozer.spec"
          fi
          echo "----- buildozer.spec (tail) -----"
          tail -n 40 buildozer.spec || true

      - name: (Optional) show android sdk state in container
        run: |
          # Many buildozer images include sdk; show what's present
          if [ -d /opt/android-sdk ]; then
            echo "/opt/android-sdk exists"
            ls -la /opt/android-sdk | head -n 40
          fi
          if command -v sdkmanager >/dev/null 2>&1; then
            sdkmanager --version || true
          fi

      - name: Build debug APK (non-interactive)
        run: |
          # Pipe 'yes' to answer any buildozer prompts (safe for CI)
          # Use verbose so logs are informative if something fails
          yes | buildozer --verbose android debug
        # If you want a release build too, uncomment the next line or add separate step:
        # run: yes | buildozer --verbose android release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: visitorapp-apk
          path: bin/*.apk
