name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ بررسی کد
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ نصب Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ نصب پیش‌نیازهای سیستم
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git ffmpeg \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-tools

      # 4️⃣ نصب Python packages
      - name: Install Python dependencies
        run: |
            pip install --upgrade pip
            pip install buildozer kivy kivymd plyer reportlab cython


      # 5️⃣ ساخت APK
      - name: Build APK
        run: |
          buildozer android debug

      # 6️⃣ ذخیره APK به عنوان artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VisitorApp-debug.apk
          path: bin/*.apk
