name: Build APK (non-container, robust)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      # SDK root inside workspace (will chown to builder)
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install base packages (sudo available on runner)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            git curl wget unzip zip tar build-essential ca-certificates \
            openjdk-17-jdk python3 python3-pip python3-setuptools python3-dev \
            python3-wheel python3-venv pkg-config \
            libstdc++6 libz-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libncurses6
          # sanity checks
          java -version || true
          python3 --version
          pip3 --version

      - name: Install Buildozer & Cython system-wide (avoid PEP 668 issues)
        run: |
          # upgrade pip system-wide (allow break-system-packages)
          python3 -m pip install --break-system-packages --upgrade pip setuptools wheel
          # install buildozer and cython system-wide; use break-system-packages to bypass PEP-668 on hosted runner
          python3 -m pip install --break-system-packages buildozer cython==0.29.36
          # confirm and capture path to console script
          BUILDOZER_BIN="$(command -v buildozer || true)"
          if [ -n "$BUILDOZER_BIN" ]; then
            echo "Found buildozer at: $BUILDOZER_BIN"
            # make sure it's executable by all users
            sudo chmod a+rx "$BUILDOZER_BIN" || true
            echo "BUILDOZER_PATH=$BUILDOZER_BIN" >> $GITHUB_ENV
          else
            echo "WARNING: buildozer not found in PATH after install" >&2
            echo "BUILDOZER_PATH=" >> $GITHUB_ENV
          fi
          # show version if available
          if [ -n "$BUILDOZER_BIN" ]; then
            "$BUILDOZER_BIN" --version || true
          fi


      - name: Ensure buildozer.spec has minimal tokens (source.dir, version)
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "Error: buildozer.spec not found in repo root" >&2
            exit 1
          fi
          if ! grep -qE '^source\.dir\s*=' buildozer.spec; then
            echo "" >> buildozer.spec
            echo "# auto-added by CI: ensure project root is used" >> buildozer.spec
            echo "source.dir = ." >> buildozer.spec
            echo "Added source.dir = . to buildozer.spec"
          fi
          if ! grep -qE '^version\s*=' buildozer.spec; then
            echo "" >> buildozer.spec
            echo "# auto-added by CI: default version" >> buildozer.spec
            echo "version = 0.1" >> buildozer.spec
            echo "Added version = 0.1 to buildozer.spec"
          fi
          echo "----- buildozer.spec (tail) -----"
          tail -n 40 buildozer.spec || true

      - name: Create non-root builder user and prepare folders
        run: |
          # create 'builder' user if not exists (safer check)
          if ! id builder >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash builder
          fi

          # create ANDROID_HOME and ensure builder owns the SDK path only
          sudo mkdir -p "$ANDROID_HOME"
          sudo chown -R builder:builder "$ANDROID_HOME"
          sudo chmod -R u+rwX,go+rX "$ANDROID_HOME" || true

          # do NOT chown the whole GITHUB_WORKSPACE — leave repo owned by runner
          echo "Note: leaving ${GITHUB_WORKSPACE} ownership unchanged to avoid git permission issues."


      - name: Download and install Android cmdline-tools (robust)
        run: |
          set -e
          CMDLINE_ZIP="commandlinetools-linux-9477386_latest.zip"
          # 1) download into /tmp (safe writeable location)
          TMP_ZIP="/tmp/${CMDLINE_ZIP}"
          curl -L -o "$TMP_ZIP" "https://dl.google.com/android/repository/${CMDLINE_ZIP}"
          # 2) extract into a tmpdir to avoid mv-into-self problems
          TMPDIR="$(mktemp -d)"
          unzip -q "$TMP_ZIP" -d "$TMPDIR"
          # 3) ensure target exists
          sudo mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          # 4) move extracted content into latest (handle different archive structures)
          if [ -d "$TMPDIR/cmdline-tools" ]; then
            sudo mv "$TMPDIR/cmdline-tools/"* "$ANDROID_HOME/cmdline-tools/latest/"
          else
            sudo mv "$TMPDIR"/* "$ANDROID_HOME/cmdline-tools/latest/"
          fi
          # 5) cleanup
          rm -rf "$TMPDIR" "$TMP_ZIP"
          # 6) set ownership so non-root builder can use SDK
          if id builder >/dev/null 2>&1; then
            sudo chown -R builder:builder "$ANDROID_HOME"
          else
            # fallback: chown to current runner user
            CURRENT_USER="$(id -un)"
            sudo chown -R "${CURRENT_USER}:${CURRENT_USER}" "$ANDROID_HOME" || true
          fi

      - name: Install Android SDK packages (platform-tools, build-tools, ndk)
        run: |
          SDKMAN="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
          # ensure sdkmanager executable permission
          sudo chmod +x "$SDKMAN" || true
          # accept licenses and install packages (run as root to avoid permission problems)
          yes | sudo "$SDKMAN" --sdk_root="$ANDROID_HOME" --licenses
          sudo "$SDKMAN" --sdk_root="$ANDROID_HOME" "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
          # chown sdk to builder so pip --user and android build tools can be used by builder
          sudo chown -R builder:builder "$ANDROID_HOME"

      - name: Verify SDK and tools
        run: |
          echo "ANDROID_HOME=${ANDROID_HOME}"
          ls -la "$ANDROID_HOME" | head -n 40
          if [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --version || true
          fi
          if [ -x "$ANDROID_HOME/platform-tools/adb" ]; then
            "$ANDROID_HOME/platform-tools/adb" version || true
          fi

      - name: Prepare perms and build as builder (fixed — use copy of workspace)
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          set -e
          RUNNER_USER="$(id -un)"
          echo "Runner user is: $RUNNER_USER"

          BUILD_WORKDIR="/tmp/ci_build_workspace"
          sudo rm -rf "$BUILD_WORKDIR"
          sudo mkdir -p "$BUILD_WORKDIR"
          sudo chown "${RUNNER_USER}:${RUNNER_USER}" "$BUILD_WORKDIR"
          sudo chmod 755 "$BUILD_WORKDIR"

          if command -v rsync >/dev/null 2>&1; then
            rsync -a --delete --exclude '.git' --no-owner --no-group "${GITHUB_WORKSPACE}/" "$BUILD_WORKDIR/"
          else
            (cd "${GITHUB_WORKSPACE}" && tar -cf - --exclude=.git .) | (cd "$BUILD_WORKDIR" && tar -xpf -)
          fi

          sudo chown -R builder:builder "$BUILD_WORKDIR"
          sudo chmod -R u+rwX,go+rX "$BUILD_WORKDIR"

          CI_SCRIPT_TMP="/tmp/ci_build.sh"
          # NOTE: BUILDOZER_PATH comes from earlier step via GITHUB_ENV
          cat > "$CI_SCRIPT_TMP" <<'BASH'
          #!/bin/bash
          set -e
          # use BUILDOZER_PATH if set, otherwise fallback
          BUILDOZER_PATH="${BUILDOZER_PATH:-}"
          export ANDROID_HOME="${ANDROID_HOME}"
          export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
          # ensure /usr/local/bin is in PATH and sdk tools in PATH
          export PATH="/usr/local/bin:/usr/bin:$PATH:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools"

          cd "${BUILD_WORKDIR}"
          echo "Running build as: $(whoami)"
          echo "Workdir: $(pwd)"
          # choose buildozer command
          if [ -n "$BUILDOZER_PATH" ] && [ -x "$BUILDOZER_PATH" ]; then
            BUILD_CMD="$BUILDOZER_PATH"
          elif command -v buildozer >/dev/null 2>&1; then
            BUILD_CMD="$(command -v buildozer)"
          else
            BUILD_CMD=""
          fi

          if [ -n "$BUILD_CMD" ]; then
            echo "Using buildozer command: $BUILD_CMD"
            yes | "$BUILD_CMD" --verbose android debug
          else
            echo "buildozer binary not found — trying python3 -m buildozer"
            # some installs expose buildozer as a module; try this as fallback
            yes | python3 -m buildozer --verbose android debug
          fi
          BASH

          # replace placeholders in the generated script with actual values we need (safe expand)
          # inject BUILD_WORKDIR and ANDROID_HOME into script
          sudo sed -i "s|\${BUILD_WORKDIR}|$BUILD_WORKDIR|g" "$CI_SCRIPT_TMP" || true
          sudo sed -i "s|\${ANDROID_HOME}|$ANDROID_HOME|g" "$CI_SCRIPT_TMP" || true

          sudo chmod 755 "$CI_SCRIPT_TMP"
          sudo chown builder:builder "$CI_SCRIPT_TMP"

          # export BUILDOZER_PATH into the builder environment when invoking
          # read from GITHUB_ENV value; if it was empty, the script will fallback
          sudo -H -u builder env BUILDOZER_PATH="${BUILDOZER_PATH:-}" bash "$CI_SCRIPT_TMP" || { echo "Builder run failed"; exit 1; }

          # after build, restore runner ownership and copy artifacts
          sudo chown -R "${RUNNER_USER}:${RUNNER_USER}" "$BUILD_WORKDIR" || true
          sudo find "$BUILD_WORKDIR" -type f -exec chmod a+r {} \; || true
          mkdir -p "${GITHUB_WORKSPACE}/.ci_artifacts"
          sudo cp -v "$BUILD_WORKDIR"/bin/*.apk "${GITHUB_WORKSPACE}/.ci_artifacts/" || true


      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: .ci_artifacts/*.apk
