name: Build APK (Debug + Release)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/emulator:${{ github.workspace }}/android-sdk/build-tools/33.0.2:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip python3-setuptools python3-wheel \
          git zip unzip openjdk-17-jdk \
          libstdc++6 libz-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          libncurses6 build-essential

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Download Android SDK Command-line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        curl -L https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Android SDK packages, build-tools, and NDK
      run: |
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"

    - name: Build Debug APK
      run: |
        buildozer android debug

    - name: Build Release APK
      run: |
        buildozer android release

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: APKs
        path: bin/*.apk
